version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
        - DataVolume1:/datavolume1
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

volumes:
    DataVolume1:
        external:
            name: DataVolume1
